add scripts
AlexeyPrikh/Sketch-Based-Modelling pull request #1
Opened 2021-04-30 18:42 UTC by AlexeyPrikh

2021-05-10 01:26 UTC, kbrodt requested changes

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +import urllib
все импорты вынести в начало скрипта

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    model = cv2.dnn.readNetFromONNX(str(MODEL_FILEPATH))
Неоптимально загружать модель на каждый вызов

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    img_kp, predicted_keypoints, confidence, predicted_heatmap = process_image(img_raw)
неоптимально делать инференс для одного и того же входа, нужно вынести

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    return y_pred, torch.tensor(y_data)
проверить, что массивы находятся на одном девайсе (цпу или гпу). Полезные методы torch.*_like или t.new_tensor(...)

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
завернуть в мейн, чтобы не было лишних переменных в глобальном скоупе, кроме констант

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    import torch.optim as optim
аналогично, импорты

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +names = list(KPS_SPIN_MAP.keys())
вынести в метод или в константы (utils)

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    img_array = np.asarray(img_sp)
преобразование координат вынести в отдельную функцию

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    shift = (size_kp[ax1]-size_kp[ax2])/2
преобразование координат вынести в отдельную функцию

2021-05-10 01:26 UTC, kbrodt commented on demo.py
> +    resized_img_size = tuple([int(x * ratio) for x in original_img_size])
преобразование координат вынести в отдельную функцию

2021-05-12 19:23 UTC, AlexeyPrikh commented on demo.py
> +    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
вот здесь не очень понял.. 
что значит "завернуть в мэйн"....

2021-05-12 20:53 UTC, kbrodt commented on demo.py
> +    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
вынести в отдельную функцию

2021-05-16 13:15 UTC, kbrodt commented on demo.py
> +def process_image_spin(img_file, bbox_file, openpose_file, input_res=224):
если bbox_file и openpose_file никогда не используются, то убрать

2021-05-16 13:15 UTC, kbrodt commented on demo.py
> +if __name__ == '__main__':
Весь код ниже вынести в отедльную функцию

2021-05-16 13:15 UTC, kbrodt commented on demo.py
> +    y_data = get_data(img_name, model_g2pe, size_sp)
Непонятное название как переменной, так и функции. Что за data?

2021-05-16 13:15 UTC, kbrodt commented on demo.py
> +# Freeze layers
Вынести в отдельную функцию

2021-05-16 13:15 UTC, kbrodt commented on demo.py
> +    fig, ax = plt.subplots(facecolor='lightgray',figsize=(16,10))
Вынести в отдульную функцию. Повторяющийся код

2021-05-16 13:15 UTC, kbrodt commented on demo.py
> +    fig, ax = plt.subplots(facecolor='lightgray',figsize=(16,10))
Вынести в отдульную функцию. Повторяющийся код

2021-05-16 19:31 UTC, AlexeyPrikh commented on demo.py
> +if __name__ == '__main__':
до меня наконец-то дошло, про глобальный скоуп, когда вынеся все в отдельную функцию у меня не увидело smpl, и я только тогда понял, что я ее в get_pred то не добавил, а только hmr

2021-05-17 07:40 UTC, merged